In [1]:
import numpy as np 
import pandas as pd

# missing vlaues and fillna()

In [2]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [3]:
df.isna().sum()
#df.isnull().sum()

A    1
B    2
C    0
dtype: int64

In [4]:
df.isna().sum().sum()

3

In [5]:
df.dropna(inplace=True)
df

A    B  C
0  1.0  5.0  1

In [6]:
df.isna().sum()

A    0
B    0
C    0
dtype: int64

In [7]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

df.fillna(value='100')

A    B  C
0  1.0  5.0  1
1  2.0  100  2
2  100  100  3

In [8]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

df['A'].fillna(value=df['A'].mean(),inplace=True)

#df['A'] = df['A'].fillna(value=df['A'].mean())

df['B'].fillna(value=df['B'].median(),inplace=True)
df

C:\Users\Dell\AppData\Local\Temp\ipykernel_17028\4081928534.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(value=df['A'].mean(),inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_17028\4081928534.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For exam

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

# impute data for missing values

In [9]:
from sklearn.impute import SimpleImputer

In [10]:
miles  = pd.DataFrame( {'miles runs ':[100,200,np.nan,56,62,np.nan,120,230,np.nan,400,210,np.nan,np.nan],
                        'playes id'  : [101,102,103,104,np.nan,105,107,108,109,110,112,np.nan,np.nan]                       
                       }
                     )
miles

miles runs   playes id
0         100.0      101.0
1         200.0      102.0
2           NaN      103.0
3          56.0      104.0
4          62.0        NaN
5           NaN      105.0
6         120.0      107.0
7         230.0      108.0
8           NaN      109.0
9         400.0      110.0
10        210.0      112.0
11          NaN        NaN
12          NaN        NaN

In [11]:
miles.isna().sum()

miles runs     5
playes id      3
dtype: int64

In [13]:
imp_mean = SimpleImputer(strategy='mean')

imp_mean.fit_transform(miles)

array([[100.  , 101.  ],
       [200.  , 102.  ],
       [172.25, 103.  ],
       [ 56.  , 104.  ],
       [ 62.  , 106.1 ],
       [172.25, 105.  ],
       [120.  , 107.  ],
       [230.  , 108.  ],
       [172.25, 109.  ],
       [400.  , 110.  ],
       [210.  , 112.  ],
       [172.25, 106.1 ],
       [172.25, 106.1 ]])

In [15]:
imp_median = SimpleImputer(strategy='median')

imp_median.fit_transform(miles)

array([[100., 101.],
       [200., 102.],
       [160., 103.],
       [ 56., 104.],
       [ 62., 106.],
       [160., 105.],
       [120., 107.],
       [230., 108.],
       [160., 109.],
       [400., 110.],
       [210., 112.],
       [160., 106.],
       [160., 106.]])

In [16]:
imp_mode = SimpleImputer(strategy='most_frequent')

imp_mode.fit_transform(miles)

array([[100., 101.],
       [200., 102.],
       [ 56., 103.],
       [ 56., 104.],
       [ 62., 101.],
       [ 56., 105.],
       [120., 107.],
       [230., 108.],
       [ 56., 109.],
       [400., 110.],
       [210., 112.],
       [ 56., 101.],
       [ 56., 101.]])

In [17]:
imp_constant = SimpleImputer(strategy='constant',fill_value = 0) # fillna(0)

imp_constant.fit_transform(miles)

array([[100., 101.],
       [200., 102.],
       [  0., 103.],
       [ 56., 104.],
       [ 62.,   0.],
       [  0., 105.],
       [120., 107.],
       [230., 108.],
       [  0., 109.],
       [400., 110.],
       [210., 112.],
       [  0.,   0.],
       [  0.,   0.]])

In [18]:
miles

miles runs   playes id
0         100.0      101.0
1         200.0      102.0
2           NaN      103.0
3          56.0      104.0
4          62.0        NaN
5           NaN      105.0
6         120.0      107.0
7         230.0      108.0
8           NaN      109.0
9         400.0      110.0
10        210.0      112.0
11          NaN        NaN
12          NaN        NaN

# make column transformations

In [19]:
from sklearn.compose import make_column_transformer

In [20]:
ct = make_column_transformer(

    (imp_median,['miles runs ', 'playes id']),

    remainder='drop'
)

ct.set_output(transform='pandas')

ColumnTransformer(transformers=[('simpleimputer',
                                 SimpleImputer(strategy='median'),
                                 ['miles runs ', 'playes id'])])

In [21]:
df_updated = ct.fit_transform(miles)
df_updated

simpleimputer__miles runs   simpleimputer__playes id
0                        100.0                     101.0
1                        200.0                     102.0
2                        160.0                     103.0
3                         56.0                     104.0
4                         62.0                     106.0
5                        160.0                     105.0
6                        120.0                     107.0
7                        230.0                     108.0
8                        160.0                     109.0
9                        400.0                     110.0
10                       210.0                     112.0
11                       160.0                     106.0
12                       160.0                     106.0

In [22]:
ct2 = make_column_transformer(

    (imp_mean,['miles runs ', 'playes id']),
    (imp_median,['miles runs ', 'playes id']),
    (imp_mode,['miles runs ', 'playes id']),
    (imp_constant,['miles runs ', 'playes id']),
    remainder='drop'
)

ct2.set_output(transform='pandas')

ColumnTransformer(transformers=[('simpleimputer-1', SimpleImputer(),
                                 ['miles runs ', 'playes id']),
                                ('simpleimputer-2',
                                 SimpleImputer(strategy='median'),
                                 ['miles runs ', 'playes id']),
                                ('simpleimputer-3',
                                 SimpleImputer(strategy='most_frequent'),
                                 ['miles runs ', 'playes id']),
                                ('simpleimputer-4',
                                 SimpleImputer(fill_value=0,
                                               strategy='constant'),
                                 ['miles runs ', 'playes id'])])

In [23]:
df_updated2 = ct2.fit_transform(miles)
df_updated2

simpleimputer-1__miles runs   simpleimputer-1__playes id  \
0                         100.00                       101.0   
1                         200.00                       102.0   
2                         172.25                       103.0   
3                          56.00                       104.0   
4                          62.00                       106.1   
5                         172.25                       105.0   
6                         120.00                       107.0   
7                         230.00                       108.0   
8                         172.25                       109.0   
9                         400.00                       110.0   
10                        210.00                       112.0   
11                        172.25                       106.1   
12                        172.25                       106.1   

    simpleimputer-2__miles runs   simpleimputer-2__playes id  \
0                          100.0                       101.0   
1                          200.0                       102.0   
2                          160.0                       103.0   
3                           56.0                       104.0   
4                           62.0                       106.0   
5                          160.0                       105.0   
6                          120.0                       107.0   
7                          230.0                       108.0   
8                          160.0                       109.0   
9                          400.0                       110.0   
10                         210.0                       112.0   
11                         160.0                       106.0   
12                         160.0                       106.0   

    simpleimputer-3__miles runs   simpleimputer-3__playes id  \
0                          100.0                       101.0   
1                          200.0                       102.0   
2                           56.0                       103.0   
3                           56.0                       104.0   
4                           62.0                       101.0   
5                           56.0                       105.0   
6                          120.0                       107.0   
7                          230.0                       108.0   
8                           56.0                       109.0   
9                          400.0                       110.0   
10                         210.0                       112.0   
11                          56.0                       101.0   
12                          56.0                       101.0   

    simpleimputer-4__miles runs   simpleimputer-4__playes id  
0                          100.0                       101.0  
1                          200.0                       102.0  
2                            0.0                       103.0  
3                           56.0                       104.0  
4                           62.0                         0.0  
5                            0.0                       105.0  
6                          120.0                       107.0  
7                          230.0                       108.0  
8                            0.0                       109.0  
9                          400.0                       110.0  
10                         210.0                       112.0  
11                           0.0                         0.0  
12                           0.0                         0.0